import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import Providers from "@/components/provider";
import RecoilWrap from "@/components/recoil";
import Layout from "@/components/Conteiner/LayoutContainer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "pinterest",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <RecoilWrap>
          <Providers>
            <Layout> {children}</Layout>
          </Providers>
        </RecoilWrap>
      </body>
    </html>
  );
}
