import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import Providers from "@/Components/provider";
import Body from "@/Components/Conteiner/BodyContainer";
import RecoilWrap from "@/Components/recoil";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "pinterest",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <RecoilWrap>
            <Body children={children} />
          </RecoilWrap>
        </Providers>
      </body>
    </html>
  );
}
