name: Deploy Project
on:
  push:
    branches:
      - main

jobs:
  deploy_pinterest:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.EC2_KEY }}

      - name: Ensure SSH directory exists
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh

      - name: Add SSH known hosts
        run: ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Install Dependencies of Front
        working-directory: ./pinterest
        run: npm i

      - name: create .env
        working-directory: ./pinterest
        run: |
          echo NEXT_PUBLIC_BASE_URL="${{ secrets.NEXT_PUBLIC_BASE_URL }}" > .env
          echo NEXT_PUBLIC_GOOGLE_CLIENT_ID="${{ secrets.NEXT_PUBLIC_GOOGLE_CLIENT_ID}}" >> .env
          echo NEXT_PUBLIC_GOOGLE_COLLBACK_URL="${{ secrets.NEXT_PUBLIC_GOOGLE_COLLBACK_URL }}" >>.env
          echo NEXT_PUBLIC_SERVER_IMG_BASE_URL="${{ secrets.NEXT_PUBLIC_SERVER_IMG_BASE_URL}}" >> .env

      - name: Build Front
        working-directory: ./pinterest
        run: npm run build

      - name: Copy Files to EC2 start next
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} '
            rm -rf /var/www/pinterestfront
            mkdir /var/www/pinterestfront'
          rsync -avz -e "ssh" ./pinterest/.next ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/var/www/pinterestfront/.next
          rsync -avz -e "ssh" ./pinterest/package.json ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/var/www/pinterestfront/package.json

      - name: Restart Nginx
        run: ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} 'sudo service nginx restart'

      - name: Start Server
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} '
            export NVM_DIR="$HOME/.nvm"
            if [ -s "$NVM_DIR/nvm.sh" ]; then
              . "$NVM_DIR/nvm.sh"
            else 
              echo "nvm.sh not found"
              exit 1
            fi
            nvm use --lts
            npm install -g pm2
            pm2 stop all

            cd /var/www/pinterestfront

            pm2 start npm --name pinterestfront -- start


           


          '
